fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.3.1
    inifile: git://github.com/puppetlabs/puppetlabs-inifile.git
  symlinks:
    yum_cron: "#{source_dir}"
